<a href="https://colab.research.google.com/github/itsayeshaqamar/flyrank-mlinternship-ayesha/blob/main/work/notebooks/capstone.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Capstone — mirrors your deployed research paper

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/itsayeshaqamar/flyrank-mlinternship-ayesha/blob/main/work/notebooks/capstone.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. Question

*The research question and the decision it supports.*

## 1. Question

### Research Question

Where do performance gaps appear across the observed organic search funnel, from search visibility to clicks, organic sessions, and engagement, and which signals are associated with these bottlenecks?

### Decision Supported

This analysis supports the decision of **which stage of the organic search journey should be investigated first when a page or observation shows weaker performance**.

### Unit of Analysis

The unit of analysis is a **page-level daily observation for a client**.

### Intended Output

The analysis will identify and rank different organic search funnel bottlenecks, such as visibility, click-through, session, or engagement gaps, and translate the observed patterns into practical, editor-facing recommendations.

### Scope

The analysis focuses on **observed relationships within the FlyRank dataset**. It does not claim to explain Google's ranking algorithm or establish causal relationships between search signals and performance.

In [1]:
# Section 1 — Research Question Configuration

PROJECT_TITLE = "Organic Search Funnel Bottleneck Analysis"

RESEARCH_QUESTION = (
    "Where do performance gaps appear across the observed organic search funnel, "
    "from search visibility to clicks, organic sessions, and engagement, "
    "and which signals are associated with these bottlenecks?"
)

DECISION_SUPPORTED = (
    "Identify which stage of the organic search journey should be investigated "
    "first when a page or observation shows weaker performance."
)

UNIT_OF_ANALYSIS = "Page-level daily observation for a client"

FUNNEL_STAGES = [
    "Search visibility",
    "Clicks",
    "Organic sessions",
    "Engagement"
]

OUTPUTS = [
    "Funnel bottleneck identification",
    "Bottleneck ranking",
    "Evidence-based recommendations"
]

SCOPE = (
    "Observed relationships within the FlyRank dataset. "
    "The analysis does not claim to explain Google's ranking algorithm "
    "or establish causal relationships."
)

print("Project:", PROJECT_TITLE)
print("Unit of analysis:", UNIT_OF_ANALYSIS)
print("Funnel stages:", " → ".join(FUNNEL_STAGES))
print("Planned outputs:", ", ".join(OUTPUTS))
print("\nResearch question:")
print(RESEARCH_QUESTION)

Project: Organic Search Funnel Bottleneck Analysis
Unit of analysis: Page-level daily observation for a client
Funnel stages: Search visibility → Clicks → Organic sessions → Engagement
Planned outputs: Funnel bottleneck identification, Bottleneck ranking, Evidence-based recommendations

Research question:
Where do performance gaps appear across the observed organic search funnel, from search visibility to clicks, organic sessions, and engagement, and which signals are associated with these bottlenecks?

## 2. Data

*Which release, which tables, date windows, what you excluded and why. Public-safe.*

In [2]:
# ============================================================
# Section 2 — Data
# ============================================================

# Install the packages needed to access the FlyRank warehouse.
!pip -q install duckdb huggingface_hub

import duckdb
import os
import pandas as pd

# ------------------------------------------------------------
# 1. Connect to DuckDB
# ------------------------------------------------------------

con = duckdb.connect()

print("DuckDB connection established.")

DuckDB connection established.

In [3]:
# ------------------------------------------------------------
# 2. Configure the FlyRank dataset
# ------------------------------------------------------------

HF_DATASET = "FlyRank/internship-warehouse"

# The capstone uses the March 2026 reporting window.
START_DATE = "2026-03-01"
END_DATE = "2026-03-31"

print("Dataset:", HF_DATASET)
print("Analysis window:", START_DATE, "to", END_DATE)

Dataset: FlyRank/internship-warehouse
Analysis window: 2026-03-01 to 2026-03-31

In [4]:
# ------------------------------------------------------------
# 3. Inspect available warehouse files/tables
# ------------------------------------------------------------

# List files available in the Hugging Face dataset.
from huggingface_hub import list_repo_files

files = list_repo_files(
    repo_id=HF_DATASET,
    repo_type="dataset"
)

print(f"Number of files found: {len(files)}")
print("\nFirst files:")
for file in files[:30]:
    print("-", file)

Number of files found: 24

First files:
- .gitattributes
- README.md
- dim_clients.parquet
- dim_content.parquet
- fact_content_daily_performance/month=2025-01/data_0.parquet
- fact_content_daily_performance/month=2025-02/data_0.parquet
- fact_content_daily_performance/month=2025-03/data_0.parquet
- fact_content_daily_performance/month=2025-04/data_0.parquet
- fact_content_daily_performance/month=2025-05/data_0.parquet
- fact_content_daily_performance/month=2025-06/data_0.parquet
- fact_content_daily_performance/month=2025-07/data_0.parquet
- fact_content_daily_performance/month=2025-08/data_0.parquet
- fact_content_daily_performance/month=2025-09/data_0.parquet
- fact_content_daily_performance/month=2025-10/data_0.parquet
- fact_content_daily_performance/month=2025-11/data_0.parquet
- fact_content_daily_performance/month=2025-12/data_0.parquet
- fact_content_daily_performance/month=2026-01/data_0.parquet
- fact_content_daily_performance/month=2026-02/data_0.parquet
- fact_content_daily_performance/month=2026-03/data_0.parquet
- fact_content_daily_performance/month=2026-04/data_0.parquet
- fact_content_daily_performance/month=2026-05/data_0.parquet
- fact_content_daily_performance/month=2026-06/data_0.parquet
- fact_content_daily_performance_sample.parquet
- fact_content_query_90d.parquet

In [5]:
# ------------------------------------------------------------
# 4. Inspect fact_content_daily_performance
# ------------------------------------------------------------

performance_files = [
    f for f in files
    if "fact_content_daily_performance" in f.lower()
]

print("Matching performance files:")
for file in performance_files:
    print("-", file)

Matching performance files:
- fact_content_daily_performance/month=2025-01/data_0.parquet
- fact_content_daily_performance/month=2025-02/data_0.parquet
- fact_content_daily_performance/month=2025-03/data_0.parquet
- fact_content_daily_performance/month=2025-04/data_0.parquet
- fact_content_daily_performance/month=2025-05/data_0.parquet
- fact_content_daily_performance/month=2025-06/data_0.parquet
- fact_content_daily_performance/month=2025-07/data_0.parquet
- fact_content_daily_performance/month=2025-08/data_0.parquet
- fact_content_daily_performance/month=2025-09/data_0.parquet
- fact_content_daily_performance/month=2025-10/data_0.parquet
- fact_content_daily_performance/month=2025-11/data_0.parquet
- fact_content_daily_performance/month=2025-12/data_0.parquet
- fact_content_daily_performance/month=2026-01/data_0.parquet
- fact_content_daily_performance/month=2026-02/data_0.parquet
- fact_content_daily_performance/month=2026-03/data_0.parquet
- fact_content_daily_performance/month=2026-04/data_0.parquet
- fact_content_daily_performance/month=2026-05/data_0.parquet
- fact_content_daily_performance/month=2026-06/data_0.parquet
- fact_content_daily_performance_sample.parquet

In [6]:
# ------------------------------------------------------------
# 4. Load and inspect the March 2026 performance table
# ------------------------------------------------------------

from huggingface_hub import hf_hub_download

MARCH_FILE = "fact_content_daily_performance/month=2026-03/data_0.parquet"

# Download the exact March 2026 partition from the public-safe
# FlyRank internship warehouse.
march_path = hf_hub_download(
    repo_id=HF_DATASET,
    filename=MARCH_FILE,
    repo_type="dataset"
)

print("March 2026 file downloaded successfully.")
print("Local path:", march_path)

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  124MB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

March 2026 file downloaded successfully.
Local path: /root/.cache/huggingface/hub/datasets--FlyRank--internship-warehouse/snapshots/50cbf7c3909d07be4d1b5906b4d09e882e5acbf2/fact_content_daily_performance/month=2026-03/data_0.parquet

In [7]:
# ------------------------------------------------------------
# 5. Inspect the March table schema
# ------------------------------------------------------------

schema = con.execute(
    f"DESCRIBE SELECT * FROM read_parquet('{march_path}')"
).df()

print("Number of columns:", len(schema))
print("\nAvailable columns:")
display(schema[["column_name", "column_type"]])

Number of columns: 31

Available columns:

                 column_name column_type
0                report_date        DATE
1             client_hash_id     VARCHAR
2            content_hash_id     VARCHAR
3             client_has_gsc     BOOLEAN
4             client_has_ga4     BOOLEAN
5         gsc_data_available     BOOLEAN
6         ga4_data_available     BOOLEAN
7            gsc_impressions      BIGINT
8                 gsc_clicks      BIGINT
9           gsc_sum_position      BIGINT
10          gsc_avg_position      DOUBLE
11             ga4_pageviews      BIGINT
12              ga4_sessions      BIGINT
13                 ga4_users      BIGINT
14      ga4_engaged_sessions      BIGINT
15  ga4_total_engagement_sec      BIGINT
16          sessions_organic      BIGINT
17           sessions_direct      BIGINT
18         sessions_referral      BIGINT
19           sessions_social      BIGINT
20             sessions_paid      BIGINT
21               sessions_ai      BIGINT
22                ai_chatgpt      BIGINT
23             ai_perplexity      BIGINT
24                 ai_gemini      BIGINT
25                ai_copilot      BIGINT
26                 ai_claude      BIGINT
27                   ai_meta      BIGINT
28                  ai_other      BIGINT
29             scroll_events      BIGINT
30                     month     VARCHAR

In [8]:
# ------------------------------------------------------------
# 6. Inspect a small sample of the March data
# ------------------------------------------------------------

march_sample = con.execute(
    f"""
    SELECT *
    FROM read_parquet('{march_path}')
    LIMIT 5
    """
).df()

print("Sample shape:", march_sample.shape)
display(march_sample)

Sample shape: (5, 31)

,report_date,client_hash_id,content_hash_id,client_has_gsc,client_has_ga4,gsc_data_available,ga4_data_available,gsc_impressions,gsc_clicks,gsc_sum_position,...,sessions_ai,ai_chatgpt,ai_perplexity,ai_gemini,ai_copilot,ai_claude,ai_meta,ai_other,scroll_events,month
0,2026-03-01,client_73cda7b4e4f265ea,content_b7e512995f79d5a6,True,False,True,<NA>,20,0,67,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2026-03
1,2026-03-01,client_73cda7b4e4f265ea,content_05597932fe4da067,True,False,True,<NA>,1,0,0,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2026-03
2,2026-03-01,client_73cda7b4e4f265ea,content_7a105f548d9c6916,True,False,True,<NA>,125,1,616,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2026-03
3,2026-03-01,client_73cda7b4e4f265ea,content_905aa32a0230694e,True,False,True,<NA>,7,0,28,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2026-03
4,2026-03-01,client_73cda7b4e4f265ea,content_a3ea9792f793ec72,True,False,True,<NA>,11,0,25,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2026-03

In [9]:
# ------------------------------------------------------------
# 7. Verify March 2026 date range and row count
# ------------------------------------------------------------

march_summary = con.execute(
    f"""
    SELECT
        COUNT(*) AS total_rows,
        MIN(report_date) AS min_date,
        MAX(report_date) AS max_date,
        COUNT(DISTINCT client_hash_id) AS clients,
        COUNT(DISTINCT content_hash_id) AS content_items
    FROM read_parquet('{march_path}')
    """
).df()

display(march_summary)

   total_rows   min_date   max_date  clients  content_items
0     9841378 2026-03-01 2026-03-31       55         331437

In [10]:
# ------------------------------------------------------------
# 8. Check coverage of the organic search funnel signals
# ------------------------------------------------------------

coverage = con.execute(
    f"""
    SELECT
        COUNT(*) AS total_rows,

        COUNT(gsc_impressions) AS impressions_available,
        COUNT(gsc_clicks) AS clicks_available,
        COUNT(gsc_avg_position) AS position_available,

        COUNT(sessions_organic) AS organic_sessions_available,
        COUNT(ga4_sessions) AS ga4_sessions_available,
        COUNT(ga4_engaged_sessions) AS engaged_sessions_available,

        COUNT(*) - COUNT(gsc_impressions) AS impressions_missing,
        COUNT(*) - COUNT(gsc_clicks) AS clicks_missing,
        COUNT(*) - COUNT(sessions_organic) AS organic_sessions_missing,
        COUNT(*) - COUNT(ga4_engaged_sessions) AS engaged_sessions_missing

    FROM read_parquet('{march_path}')
    """
).df()

display(coverage)

,total_rows,impressions_available,clicks_available,position_available,organic_sessions_available,ga4_sessions_available,engaged_sessions_available,impressions_missing,clicks_missing,organic_sessions_missing,engaged_sessions_missing
0,9841378,9841378,9841378,3611061,6822637,6822637,6822637,0,0,3018741,3018741

In [11]:
# ------------------------------------------------------------
# 9. Convert coverage counts into percentages
# ------------------------------------------------------------

coverage_pct = pd.DataFrame({
    "Signal": [
        "GSC impressions",
        "GSC clicks",
        "GSC average position",
        "Organic sessions",
        "GA4 sessions",
        "GA4 engaged sessions"
    ],
    "Available (%)": [
        coverage.loc[0, "impressions_available"] / coverage.loc[0, "total_rows"] * 100,
        coverage.loc[0, "clicks_available"] / coverage.loc[0, "total_rows"] * 100,
        coverage.loc[0, "position_available"] / coverage.loc[0, "total_rows"] * 100,
        coverage.loc[0, "organic_sessions_available"] / coverage.loc[0, "total_rows"] * 100,
        coverage.loc[0, "ga4_sessions_available"] / coverage.loc[0, "total_rows"] * 100,
        coverage.loc[0, "engaged_sessions_available"] / coverage.loc[0, "total_rows"] * 100
    ]
})

coverage_pct["Available (%)"] = coverage_pct["Available (%)"].round(2)

display(coverage_pct)

                 Signal  Available (%)
0       GSC impressions         100.00
1            GSC clicks         100.00
2  GSC average position          36.69
3      Organic sessions          69.33
4          GA4 sessions          69.33
5  GA4 engaged sessions          69.33

In [12]:
# ------------------------------------------------------------
# 10. Inspect GSC and GA4 availability patterns
# ------------------------------------------------------------

availability_summary = con.execute(
    f"""
    SELECT
        client_has_gsc,
        client_has_ga4,
        gsc_data_available,
        ga4_data_available,
        COUNT(*) AS rows
    FROM read_parquet('{march_path}')
    GROUP BY
        client_has_gsc,
        client_has_ga4,
        gsc_data_available,
        ga4_data_available
    ORDER BY rows DESC
    """
).df()

display(availability_summary)

,client_has_gsc,client_has_ga4,gsc_data_available,ga4_data_available,rows
0,True,True,False,False,4690323
1,True,True,True,False,1718348
2,True,False,True,<NA>,1528366
3,True,False,False,<NA>,1490375
4,True,True,True,True,364347
5,True,True,False,True,49619

In [13]:
# ------------------------------------------------------------
# 11. Basic validity checks for funnel metrics
# ------------------------------------------------------------

validity = con.execute(
    f"""
    SELECT
        MIN(gsc_impressions) AS min_impressions,
        MAX(gsc_impressions) AS max_impressions,

        MIN(gsc_clicks) AS min_clicks,
        MAX(gsc_clicks) AS max_clicks,

        MIN(gsc_avg_position) AS min_position,
        MAX(gsc_avg_position) AS max_position,

        MIN(sessions_organic) AS min_organic_sessions,
        MAX(sessions_organic) AS max_organic_sessions,

        MIN(ga4_engaged_sessions) AS min_engaged_sessions,
        MAX(ga4_engaged_sessions) AS max_engaged_sessions

    FROM read_parquet('{march_path}')
    """
).df()

display(validity)

,min_impressions,max_impressions,min_clicks,max_clicks,min_position,max_position,min_organic_sessions,max_organic_sessions,min_engaged_sessions,max_engaged_sessions
0,0,40084,0,274,0.0,498.0,0,405,0,21

In [14]:
# ------------------------------------------------------------
# 12. Final March 2026 dataset summary
# ------------------------------------------------------------

data_summary = con.execute(
    f"""
    SELECT
        COUNT(*) AS total_rows,
        MIN(report_date) AS start_date,
        MAX(report_date) AS end_date,
        COUNT(DISTINCT client_hash_id) AS unique_clients,
        COUNT(DISTINCT content_hash_id) AS unique_content_items
    FROM read_parquet('{march_path}')
    """
).df()

display(data_summary)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

   total_rows start_date   end_date  unique_clients  unique_content_items
0     9841378 2026-03-01 2026-03-31              55                331437

In [15]:
# ------------------------------------------------------------
# 13. Define the funnel fields and excluded fields
# ------------------------------------------------------------

FUNNEL_COLUMNS = {
    "visibility": "gsc_impressions",
    "clicks": "gsc_clicks",
    "sessions": "sessions_organic",
    "engagement": "ga4_engaged_sessions",
    "position": "gsc_avg_position"
}

EXCLUDED_COLUMNS = {
    "client_hash_id": "Identifier; not a modeling signal",
    "content_hash_id": "Identifier; not a modeling signal",
    "month": "Partition/helper field; report_date is used for the analysis window"
}

print("Funnel fields:")
for stage, column in FUNNEL_COLUMNS.items():
    print(f"- {stage}: {column}")

print("\nExcluded fields:")
for column, reason in EXCLUDED_COLUMNS.items():
    print(f"- {column}: {reason}")

Funnel fields:
- visibility: gsc_impressions
- clicks: gsc_clicks
- sessions: sessions_organic
- engagement: ga4_engaged_sessions
- position: gsc_avg_position

Excluded fields:
- client_hash_id: Identifier; not a modeling signal
- content_hash_id: Identifier; not a modeling signal
- month: Partition/helper field; report_date is used for the analysis window

In [16]:
# ------------------------------------------------------------
# 14. Create the analysis dataset
# ------------------------------------------------------------

analysis_columns = [
    "report_date",
    "client_hash_id",
    "content_hash_id",
    "gsc_impressions",
    "gsc_clicks",
    "gsc_avg_position",
    "sessions_organic",
    "ga4_engaged_sessions"
]

analysis_df = con.execute(
    f"""
    SELECT
        report_date,
        client_hash_id,
        content_hash_id,
        gsc_impressions,
        gsc_clicks,
        gsc_avg_position,
        sessions_organic,
        ga4_engaged_sessions
    FROM read_parquet('{march_path}')
    WHERE report_date BETWEEN DATE '{START_DATE}' AND DATE '{END_DATE}'
    """
).df()

print("Analysis dataset shape:", analysis_df.shape)
print("\nColumns:")
print(list(analysis_df.columns))

display(analysis_df.head())

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Analysis dataset shape: (9841378, 8)

Columns:
['report_date', 'client_hash_id', 'content_hash_id', 'gsc_impressions', 'gsc_clicks', 'gsc_avg_position', 'sessions_organic', 'ga4_engaged_sessions']

,report_date,client_hash_id,content_hash_id,gsc_impressions,gsc_clicks,gsc_avg_position,sessions_organic,ga4_engaged_sessions
0,2026-03-01,client_73cda7b4e4f265ea,content_b7e512995f79d5a6,20,0,3.350000,<NA>,<NA>
1,2026-03-01,client_73cda7b4e4f265ea,content_05597932fe4da067,1,0,0.000000,<NA>,<NA>
2,2026-03-01,client_73cda7b4e4f265ea,content_7a105f548d9c6916,125,1,4.928000,<NA>,<NA>
3,2026-03-01,client_73cda7b4e4f265ea,content_905aa32a0230694e,7,0,4.000000,<NA>,<NA>
4,2026-03-01,client_73cda7b4e4f265ea,content_a3ea9792f793ec72,11,0,2.272727,<NA>,<NA>

In [17]:
# ------------------------------------------------------------
# 15. Validate the analysis dataset
# ------------------------------------------------------------

print("Date range:")
print(analysis_df["report_date"].min(), "to", analysis_df["report_date"].max())

print("\nRows:", len(analysis_df))
print("Unique clients:", analysis_df["client_hash_id"].nunique())
print("Unique content items:", analysis_df["content_hash_id"].nunique())

print("\nMissing values:")
display(
    analysis_df.isna().sum().to_frame("missing_values")
)

Date range:
2026-03-01 00:00:00 to 2026-03-31 00:00:00

Rows: 9841378
Unique clients: 55
Unique content items: 331437

Missing values:

                      missing_values
report_date                        0
client_hash_id                     0
content_hash_id                    0
gsc_impressions                    0
gsc_clicks                         0
gsc_avg_position             6230317
sessions_organic             3018741
ga4_engaged_sessions         3018741

## 3. Methodology

*Assumptions, features, label definition, baseline, validation design, leakage checks.*

## 3. Methodology

### Analysis Approach

The analysis treats organic search performance as an observed funnel:

**GSC impressions → GSC clicks → organic sessions → engaged sessions**

The goal is not to predict a hidden or ground-truth bottleneck label. Instead, the analysis uses observed search and traffic measurements to identify where relatively weak performance appears within the funnel.

Because GSC and GA4 are different measurement systems, their values are not assumed to represent a strict user-level conversion path.

### Features

The analysis uses:

- `gsc_impressions` — observed search visibility
- `gsc_clicks` — observed search clicks
- `gsc_avg_position` — observed average search position
- `sessions_organic` — observed organic sessions
- `ga4_engaged_sessions` — observed engaged sessions

The following derived signals are used:

- **CTR** = GSC clicks / GSC impressions
- **Engagement rate** = GA4 engaged sessions / organic sessions
- **Organic-session availability** — whether organic session data is present
- **Average position** — used as a visibility/context signal

The organic-session-to-GSC-click ratio was investigated but is not used as a primary bottleneck score because it compares measurements from different systems and produces highly skewed values, particularly when GSC click counts are very small.

### Bottleneck Definition

A bottleneck represents a relatively weak observed signal at a particular stage of the search funnel.

The analysis uses data-driven thresholds based on the observed March 2026 distributions rather than fixed SEO benchmarks.

CTR is evaluated among observations with measurable search impressions and positive clicks. Zero-click observations are treated separately because the overall CTR distribution is dominated by zero-click rows.

Engagement is evaluated only where organic sessions and engaged sessions are both available and organic sessions are greater than zero.

Average position is evaluated only where a valid position measurement is available. Higher position values represent relatively weaker observed search position.

### Missing Data

Missing GSC or GA4 measurements are treated as unavailable observations rather than zero performance.

This distinction is important because approximately 30.67% of March observations have no organic-session measurement. Missing traffic data therefore cannot automatically be interpreted as zero traffic.

### Baseline

The baseline is a transparent rule-based approach using individual observed funnel signals without combining them into a multi-stage score.

The proposed scoring approach will then combine normalized stage-level signals to produce a ranked bottleneck output.

### Validation Design

There is no observed ground-truth bottleneck label in the warehouse. Therefore, the analysis does not claim classification accuracy.

Validation focuses on:

- signal coverage,
- distribution checks,
- sensitivity to the selected thresholds,
- consistency of the resulting rankings,
- and comparison against the simple rule-based baseline.

### Leakage Checks

The analysis uses only measurements available within the same page-level daily observation.

`client_hash_id` and `content_hash_id` are retained only for identifying observations in the final output and are not used as predictive signals.

The `month` partition field is excluded from the analytical features because the analysis window is defined using `report_date`.

No future observations are used to construct the current-period bottleneck signals.

### Interpretation

The resulting bottleneck categories and rankings represent **observed, directional decision support**.

They do not establish causality, prove Google's ranking algorithm, or guarantee that changing a particular signal will improve search performance.

In [18]:
# ============================================================
# Section 3 — Methodology
# 1. Create observed funnel efficiency metrics
# ============================================================

import numpy as np

funnel_df = analysis_df.copy()

# ------------------------------------------------------------
# CTR: clicks generated from search impressions
# ------------------------------------------------------------
funnel_df["ctr"] = np.where(
    funnel_df["gsc_impressions"] > 0,
    funnel_df["gsc_clicks"] / funnel_df["gsc_impressions"],
    np.nan
)

# ------------------------------------------------------------
# Session capture rate:
# organic sessions relative to GSC clicks
#
# This is treated as an observed cross-system efficiency
# signal, not as a strict user-level conversion rate.
# ------------------------------------------------------------
funnel_df["session_capture_rate"] = np.where(
    (funnel_df["gsc_clicks"] > 0) &
    funnel_df["sessions_organic"].notna(),
    funnel_df["sessions_organic"] / funnel_df["gsc_clicks"],
    np.nan
)

# ------------------------------------------------------------
# Engagement rate:
# engaged sessions relative to organic sessions
# ------------------------------------------------------------
funnel_df["engagement_rate"] = np.where(
    (funnel_df["sessions_organic"] > 0) &
    funnel_df["ga4_engaged_sessions"].notna(),
    funnel_df["ga4_engaged_sessions"] / funnel_df["sessions_organic"],
    np.nan
)

print("Funnel metrics created.")

display(
    funnel_df[
        [
            "gsc_impressions",
            "gsc_clicks",
            "sessions_organic",
            "ga4_engaged_sessions",
            "ctr",
            "session_capture_rate",
            "engagement_rate"
        ]
    ].head(10)
)

Funnel metrics created.

,gsc_impressions,gsc_clicks,sessions_organic,ga4_engaged_sessions,ctr,session_capture_rate,engagement_rate
0,20,0,<NA>,<NA>,0.000000,NaN,NaN
1,1,0,<NA>,<NA>,0.000000,NaN,NaN
2,125,1,<NA>,<NA>,0.008000,NaN,NaN
3,7,0,<NA>,<NA>,0.000000,NaN,NaN
4,11,0,<NA>,<NA>,0.000000,NaN,NaN
5,239,1,<NA>,<NA>,0.004184,NaN,NaN
6,191,0,<NA>,<NA>,0.000000,NaN,NaN
7,55,0,<NA>,<NA>,0.000000,NaN,NaN
8,77,0,<NA>,<NA>,0.000000,NaN,NaN
9,2,0,<NA>,<NA>,0.000000,NaN,NaN

In [19]:
# ============================================================
# 2. Validate derived funnel metrics
# ============================================================

metric_summary = funnel_df[
    [
        "ctr",
        "session_capture_rate",
        "engagement_rate"
    ]
].describe(
    percentiles=[0.01, 0.05, 0.25, 0.50, 0.75, 0.95, 0.99]
).T

display(metric_summary)

,count,mean,std,min,1%,5%,25%,50%,75%,95%,99%,max
ctr,3611061.0,0.003081,0.030092,0.0,0.0,0.0,0.0,0.0,0.0,0.011111,0.05,1.0
session_capture_rate,246967.0,1.007862,1.179250,0.0,0.0,0.0,0.0,1.0,1.5,3.000000,5.00,48.5
engagement_rate,212643.0,0.034490,0.122785,0.0,0.0,0.0,0.0,0.0,0.0,0.333333,0.50,5.0

In [20]:
# ============================================================
# 3. Coverage of derived funnel metrics
# ============================================================

metric_coverage = pd.DataFrame({
    "Metric": [
        "CTR",
        "Session capture rate",
        "Engagement rate"
    ],
    "Available rows": [
        funnel_df["ctr"].notna().sum(),
        funnel_df["session_capture_rate"].notna().sum(),
        funnel_df["engagement_rate"].notna().sum()
    ]
})

metric_coverage["Coverage (%)"] = (
    metric_coverage["Available rows"] /
    len(funnel_df) * 100
).round(2)

display(metric_coverage)

                 Metric  Available rows  Coverage (%)
0                   CTR         3611061         36.69
1  Session capture rate          246967          2.51
2       Engagement rate          212643          2.16

In [21]:
# ============================================================
# 4. Inspect potentially unusual funnel rates
# ============================================================

print("CTR above 100%:")
print((funnel_df["ctr"] > 1).sum())

print("\nSession capture rate above 100%:")
print((funnel_df["session_capture_rate"] > 1).sum())

print("\nEngagement rate above 100%:")
print((funnel_df["engagement_rate"] > 1).sum())

CTR above 100%:
0

Session capture rate above 100%:
71325

Engagement rate above 100%:
30

In [22]:
# ============================================================
# 5. Inspect extreme observations
# ============================================================

extreme_capture = (
    funnel_df[
        funnel_df["session_capture_rate"].notna()
    ]
    .sort_values("session_capture_rate", ascending=False)
    [
        [
            "report_date",
            "gsc_clicks",
            "sessions_organic",
            "session_capture_rate"
        ]
    ]
    .head(10)
)

print("Highest session-capture observations:")
display(extreme_capture)

Highest session-capture observations:

        report_date  gsc_clicks  sessions_organic  session_capture_rate
90984    2026-03-03           2                97             48.500000
93302    2026-03-03           2                81             40.500000
90251    2026-03-03           1                31             31.000000
9652611  2026-03-28           1                27             27.000000
1612070  2026-03-02           1                26             26.000000
1691316  2026-03-04           3                77             25.666667
5766553  2026-03-18           1                24             24.000000
7575339  2026-03-24           1                23             23.000000
1414531  2026-03-05           2                42             21.000000
346477   2026-03-03           1                20             20.000000

In [23]:
# ============================================================
# Section 3 — Methodology
# 6. Investigate cross-system ratio behavior
# ============================================================

# ------------------------------------------------------------
# Organic sessions / GSC clicks
# ------------------------------------------------------------

capture_above_1 = funnel_df[
    funnel_df["session_capture_rate"] > 1
].copy()

print("Observations with organic-session-to-click ratio > 1:")
print(len(capture_above_1))

print("\nExamples:")
display(
    capture_above_1[
        [
            "report_date",
            "gsc_impressions",
            "gsc_clicks",
            "sessions_organic",
            "session_capture_rate"
        ]
    ]
    .sort_values("session_capture_rate", ascending=False)
    .head(10)
)

Observations with organic-session-to-click ratio > 1:
71325

Examples:

,report_date,gsc_impressions,gsc_clicks,sessions_organic,session_capture_rate
90984,2026-03-03,1379,2,97,48.500000
93302,2026-03-03,1392,2,81,40.500000
90251,2026-03-03,144,1,31,31.000000
9652611,2026-03-28,1511,1,27,27.000000
1612070,2026-03-02,392,1,26,26.000000
1691316,2026-03-04,1107,3,77,25.666667
5766553,2026-03-18,77,1,24,24.000000
7575339,2026-03-24,365,1,23,23.000000
1414531,2026-03-05,433,2,42,21.000000
9649243,2026-03-28,278,1,20,20.000000

In [24]:
# ============================================================
# 7. Investigate engagement ratios above 100%
# ============================================================

engagement_above_1 = funnel_df[
    funnel_df["engagement_rate"] > 1
].copy()

print("Observations with engagement ratio > 1:")
print(len(engagement_above_1))

print("\nExamples:")
display(
    engagement_above_1[
        [
            "report_date",
            "sessions_organic",
            "ga4_engaged_sessions",
            "engagement_rate"
        ]
    ]
    .sort_values("engagement_rate", ascending=False)
    .head(10)
)

Observations with engagement ratio > 1:
30

Examples:

        report_date  sessions_organic  ga4_engaged_sessions  engagement_rate
1694376  2026-03-04                 1                     5              5.0
3216254  2026-03-10                 1                     4              4.0
715878   2026-03-04                 2                     5              2.5
959110   2026-03-06                 1                     2              2.0
1960891  2026-03-07                 1                     2              2.0
1867702  2026-03-07                 1                     2              2.0
5880978  2026-03-20                 1                     2              2.0
5354898  2026-03-19                 1                     2              2.0
4516805  2026-03-17                 1                     2              2.0
5351001  2026-03-19                 1                     2              2.0

In [25]:
# ============================================================
# 8. Distribution of the ratio signals
# ============================================================

ratio_summary = funnel_df[
    [
        "session_capture_rate",
        "engagement_rate"
    ]
].describe(
    percentiles=[
        0.01,
        0.05,
        0.10,
        0.25,
        0.50,
        0.75,
        0.90,
        0.95,
        0.99
    ]
).T

display(ratio_summary)

,count,mean,std,min,1%,5%,10%,25%,50%,75%,90%,95%,99%,max
session_capture_rate,246967.0,1.007862,1.179250,0.0,0.0,0.0,0.0,0.0,1.0,1.5,2.000000,3.000000,5.0,48.5
engagement_rate,212643.0,0.034490,0.122785,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.058824,0.333333,0.5,5.0

In [26]:
# ============================================================
# Section 3 — Methodology
# 6. Prepare robust funnel signals
# ============================================================

# Work on a copy so the original analysis dataset remains unchanged.
model_df = funnel_df.copy()

# ------------------------------------------------------------
# Primary search efficiency metric
# ------------------------------------------------------------

# CTR is valid when impressions are greater than zero.
model_df["ctr"] = np.where(
    model_df["gsc_impressions"] > 0,
    model_df["gsc_clicks"] / model_df["gsc_impressions"],
    np.nan
)

# ------------------------------------------------------------
# Organic session availability
# ------------------------------------------------------------

model_df["organic_sessions_available"] = (
    model_df["sessions_organic"].notna()
)

# ------------------------------------------------------------
# Engagement availability
# ------------------------------------------------------------

model_df["engagement_available"] = (
    model_df["ga4_engaged_sessions"].notna() &
    model_df["sessions_organic"].notna() &
    (model_df["sessions_organic"] > 0)
)

# ------------------------------------------------------------
# Engagement rate
# Used only where organic sessions are available and > 0.
# ------------------------------------------------------------

model_df["engagement_rate"] = np.where(
    model_df["engagement_available"],
    model_df["ga4_engaged_sessions"] /
    model_df["sessions_organic"],
    np.nan
)

print("Prepared funnel signals.")

Prepared funnel signals.

In [31]:
# ============================================================
# Section 3 — Methodology
# 11. Define eligible populations for each funnel diagnostic
# ============================================================

# Search observations with actual impressions.
ctr_eligible = model_df[
    model_df["gsc_impressions"] > 0
].copy()

# Observations that received at least one GSC click.
positive_click_eligible = model_df[
    (model_df["gsc_impressions"] > 0) &
    (model_df["gsc_clicks"] > 0)
].copy()

# Observations with measurable organic sessions and
# at least one organic session.
engagement_eligible = model_df[
    model_df["sessions_organic"].notna() &
    (model_df["sessions_organic"] > 0) &
    model_df["ga4_engaged_sessions"].notna()
].copy()

print("Eligible populations")
print("--------------------")
print("Impression-eligible:", len(ctr_eligible))
print("Positive-click eligible:", len(positive_click_eligible))
print("Engagement eligible:", len(engagement_eligible))

Eligible populations
--------------------
Impression-eligible: 3611061
Positive-click eligible: 417981
Engagement eligible: 212643

In [40]:
# ============================================================
# Section 3 — Methodology
# 7. Define defensible funnel metrics
# ============================================================

# Work from the prepared model dataset.
analysis_df = model_df.copy()

# ------------------------------------------------------------
# 1. CTR
# ------------------------------------------------------------
# CTR is a direct GSC ratio and is only calculated when
# impressions are greater than zero.

analysis_df["ctr"] = np.where(
    analysis_df["gsc_impressions"] > 0,
    analysis_df["gsc_clicks"] / analysis_df["gsc_impressions"],
    np.nan
)

# ------------------------------------------------------------
# 2. Session-to-click ratio
# ------------------------------------------------------------
# This is treated as a descriptive cross-system ratio,
# NOT as a conversion rate.
#
# GSC clicks and GA4 organic sessions are measured by
# different systems, so values above 1 are possible.

analysis_df["session_to_click_ratio"] = np.where(
    (
        analysis_df["gsc_clicks"] > 0
    ) &
    (
        analysis_df["sessions_organic"].notna()
    ),
    analysis_df["sessions_organic"] /
    analysis_df["gsc_clicks"],
    np.nan
)

# ------------------------------------------------------------
# 3. Engaged-session ratio
# ------------------------------------------------------------
# This is also treated as a descriptive ratio because
# the observed data contains some values above 1.

analysis_df["engaged_session_ratio"] = np.where(
    (
        analysis_df["sessions_organic"] > 0
    ) &
    (
        analysis_df["ga4_engaged_sessions"].notna()
    ),
    analysis_df["ga4_engaged_sessions"] /
    analysis_df["sessions_organic"],
    np.nan
)

# ------------------------------------------------------------
# 4. Availability indicators
# ------------------------------------------------------------

analysis_df["gsc_available"] = (
    analysis_df["gsc_impressions"].notna()
)

analysis_df["click_observation_available"] = (
    analysis_df["gsc_impressions"].notna()
)

analysis_df["organic_sessions_available"] = (
    analysis_df["sessions_organic"].notna()
)

analysis_df["engagement_available"] = (
    analysis_df["ga4_engaged_sessions"].notna()
    &
    analysis_df["sessions_organic"].notna()
)

print("Defensible funnel metrics created.")

print("\nEligible populations")
print("--------------------")
print(
    "Impression-eligible:",
    analysis_df["gsc_impressions"].gt(0).sum()
)

print(
    "Positive-click eligible:",
    analysis_df["gsc_clicks"].gt(0).sum()
)

print(
    "Session-ratio eligible:",
    analysis_df["session_to_click_ratio"].notna().sum()
)

print(
    "Engagement-ratio eligible:",
    analysis_df["engaged_session_ratio"].notna().sum()
)

Defensible funnel metrics created.

Eligible populations
--------------------
Impression-eligible: 3611061
Positive-click eligible: 417981
Session-ratio eligible: 246967
Engagement-ratio eligible: 212643

In [41]:
# ============================================================
# 8. Validate the revised metrics
# ============================================================

metric_checks = pd.DataFrame({
    "Metric": [
        "CTR",
        "Session-to-click ratio",
        "Engaged-session ratio"
    ],
    "Available rows": [
        analysis_df["ctr"].notna().sum(),
        analysis_df["session_to_click_ratio"].notna().sum(),
        analysis_df["engaged_session_ratio"].notna().sum()
    ],
    "Above 1": [
        (analysis_df["ctr"] > 1).sum(),
        (analysis_df["session_to_click_ratio"] > 1).sum(),
        (analysis_df["engaged_session_ratio"] > 1).sum()
    ]
})

metric_checks["Coverage (%)"] = (
    metric_checks["Available rows"] /
    len(analysis_df) * 100
).round(2)

display(metric_checks)

                   Metric  Available rows  Above 1  Coverage (%)
0                     CTR         3611061        0         36.69
1  Session-to-click ratio          246967    71325          2.51
2   Engaged-session ratio          212643       30          2.16

In [32]:
# ============================================================
# 12. CTR distribution among observations with clicks
# ============================================================

ctr_positive_summary = positive_click_eligible["ctr"].describe(
    percentiles=[
        0.01,
        0.05,
        0.10,
        0.25,
        0.50,
        0.75,
        0.90,
        0.95,
        0.99
    ]
)

display(ctr_positive_summary)

count    417981.000000
mean          0.026615
std           0.084832
min           0.000025
1%            0.000862
5%            0.001748
10%           0.002532
25%           0.004651
50%           0.009259
75%           0.019355
90%           0.043478
95%           0.080000
99%           0.333333
max           1.000000
Name: ctr, dtype: float64

In [33]:
# ============================================================
# 13. Engagement distribution among measurable traffic
# ============================================================

engagement_summary = engagement_eligible["engagement_rate"].describe(
    percentiles=[
        0.01,
        0.05,
        0.10,
        0.25,
        0.50,
        0.75,
        0.90,
        0.95,
        0.99
    ]
)

display(engagement_summary)

count    212643.000000
mean          0.034490
std           0.122785
min           0.000000
1%            0.000000
5%            0.000000
10%           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
90%           0.058824
95%           0.333333
99%           0.500000
max           5.000000
Name: engagement_rate, dtype: float64

In [34]:
# ============================================================
# 14. Search-position distribution
# ============================================================

position_eligible = model_df[
    model_df["gsc_avg_position"].notna()
].copy()

position_summary = position_eligible["gsc_avg_position"].describe(
    percentiles=[
        0.10,
        0.25,
        0.50,
        0.75,
        0.90
    ]
)

display(position_summary)

count    3.611061e+06
mean     1.582665e+01
std      1.985603e+01
min      0.000000e+00
10%      1.500000e+00
25%      3.742120e+00
50%      7.500000e+00
75%      2.020000e+01
90%      4.300000e+01
max      4.980000e+02
Name: gsc_avg_position, dtype: float64

In [35]:
# ============================================================
# 15. Zero-click observations
# ============================================================

zero_clicks = (
    (model_df["gsc_impressions"] > 0) &
    (model_df["gsc_clicks"] == 0)
)

zero_click_summary = pd.DataFrame({
    "Category": [
        "Impressions > 0 and clicks = 0",
        "Impressions > 0 and clicks > 0"
    ],
    "Rows": [
        zero_clicks.sum(),
        positive_click_eligible.shape[0]
    ]
})

zero_click_summary["Percentage (%)"] = (
    zero_click_summary["Rows"] /
    ctr_eligible.shape[0] * 100
).round(2)

display(zero_click_summary)

                         Category     Rows  Percentage (%)
0  Impressions > 0 and clicks = 0  3193080           88.42
1  Impressions > 0 and clicks > 0   417981           11.58

In [36]:
# ============================================================
# Section 3 — Methodology
# 12. CTR distribution among observations with positive clicks
# ============================================================

positive_click_eligible = model_df[
    (model_df["gsc_impressions"] > 0) &
    (model_df["gsc_clicks"] > 0)
].copy()

ctr_summary = positive_click_eligible["ctr"].describe(
    percentiles=[
        0.01,
        0.05,
        0.10,
        0.25,
        0.50,
        0.75,
        0.90,
        0.95,
        0.99
    ]
)

display(ctr_summary)

count    417981.000000
mean          0.026615
std           0.084832
min           0.000025
1%            0.000862
5%            0.001748
10%           0.002532
25%           0.004651
50%           0.009259
75%           0.019355
90%           0.043478
95%           0.080000
99%           0.333333
max           1.000000
Name: ctr, dtype: float64

In [37]:
# ============================================================
# 13. Engagement distribution among measurable organic traffic
# ============================================================

engagement_eligible = model_df[
    model_df["sessions_organic"].notna() &
    (model_df["sessions_organic"] > 0) &
    model_df["ga4_engaged_sessions"].notna()
].copy()

engagement_summary = engagement_eligible["engagement_rate"].describe(
    percentiles=[
        0.01,
        0.05,
        0.10,
        0.25,
        0.50,
        0.75,
        0.90,
        0.95,
        0.99
    ]
)

display(engagement_summary)

count    212643.000000
mean          0.034490
std           0.122785
min           0.000000
1%            0.000000
5%            0.000000
10%           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
90%           0.058824
95%           0.333333
99%           0.500000
max           5.000000
Name: engagement_rate, dtype: float64

In [38]:
# ============================================================
# 14. Search-position distribution
# ============================================================

position_eligible = model_df[
    model_df["gsc_avg_position"].notna()
].copy()

position_summary = position_eligible["gsc_avg_position"].describe(
    percentiles=[
        0.10,
        0.25,
        0.50,
        0.75,
        0.90,
        0.95
    ]
)

display(position_summary)

count    3.611061e+06
mean     1.582665e+01
std      1.985603e+01
min      0.000000e+00
10%      1.500000e+00
25%      3.742120e+00
50%      7.500000e+00
75%      2.020000e+01
90%      4.300000e+01
95%      6.275000e+01
max      4.980000e+02
Name: gsc_avg_position, dtype: float64

In [39]:
# ============================================================
# 15. Zero-click observations
# ============================================================

zero_clicks = (
    (model_df["gsc_impressions"] > 0) &
    (model_df["gsc_clicks"] == 0)
)

positive_clicks = (
    (model_df["gsc_impressions"] > 0) &
    (model_df["gsc_clicks"] > 0)
)

zero_click_summary = pd.DataFrame({
    "Category": [
        "Impressions > 0 and clicks = 0",
        "Impressions > 0 and clicks > 0"
    ],
    "Rows": [
        zero_clicks.sum(),
        positive_clicks.sum()
    ]
})

zero_click_summary["Percentage (%)"] = (
    zero_click_summary["Rows"] /
    (zero_clicks.sum() + positive_clicks.sum()) * 100
).round(2)

display(zero_click_summary)

                         Category     Rows  Percentage (%)
0  Impressions > 0 and clicks = 0  3193080           88.42
1  Impressions > 0 and clicks > 0   417981           11.58

In [42]:
# ============================================================
# Section 3 — Methodology
# 9. Define data-driven bottleneck thresholds
# ============================================================

# ------------------------------------------------------------
# Thresholds are calculated from the observed data.
# No universal SEO thresholds are assumed.
# ------------------------------------------------------------

# CTR threshold:
# 25th percentile among observations with impressions > 0.
ctr_threshold = analysis_df.loc[
    analysis_df["ctr"].notna(),
    "ctr"
].quantile(0.25)

# Position threshold:
# 75th percentile among observations with a valid position.
# Higher position values indicate weaker average visibility.
position_threshold = analysis_df.loc[
    analysis_df["gsc_avg_position"].notna() &
    (analysis_df["gsc_avg_position"] > 0),
    "gsc_avg_position"
].quantile(0.75)

# Session-to-click ratio:
# We use the median as a descriptive reference point rather
# than treating the ratio as a true conversion rate.
session_ratio_threshold = analysis_df.loc[
    analysis_df["session_to_click_ratio"].notna(),
    "session_to_click_ratio"
].median()

# Engagement ratio:
# Because this metric has extremely sparse coverage and many
# zero values, use the 90th percentile only as a descriptive
# reference rather than a universal benchmark.
engagement_ratio_threshold = analysis_df.loc[
    analysis_df["engaged_session_ratio"].notna(),
    "engaged_session_ratio"
].quantile(0.90)

print("Data-driven thresholds")
print("----------------------")
print(f"CTR 25th percentile: {ctr_threshold:.6f}")
print(f"Position 75th percentile: {position_threshold:.2f}")
print(f"Session-to-click median: {session_ratio_threshold:.2f}")
print(f"Engaged-session ratio 90th percentile: {engagement_ratio_threshold:.4f}")

Data-driven thresholds
----------------------
CTR 25th percentile: 0.000000
Position 75th percentile: 21.35
Session-to-click median: 1.00
Engaged-session ratio 90th percentile: 0.0588

In [43]:
# ============================================================
# Section 3 — Methodology
# 10. Define observable bottleneck indicators
# ============================================================

# Work on the analysis dataset.
bottleneck_df = analysis_df.copy()

# ------------------------------------------------------------
# 1. Visibility bottleneck
# ------------------------------------------------------------
# An observation is considered visibility-constrained when
# it has measurable GSC impressions but its average position
# is worse than the observed 75th percentile.
#
# This is a relative threshold, not a universal SEO standard.

bottleneck_df["visibility_bottleneck"] = (
    (bottleneck_df["gsc_impressions"] > 0) &
    (bottleneck_df["gsc_avg_position"].notna()) &
    (bottleneck_df["gsc_avg_position"] > position_threshold)
)

# ------------------------------------------------------------
# 2. Click bottleneck
# ------------------------------------------------------------
# An observation is considered a click bottleneck when it
# receives search impressions but no GSC clicks.
#
# This avoids using the zero CTR percentile as a threshold.

bottleneck_df["click_bottleneck"] = (
    (bottleneck_df["gsc_impressions"] > 0) &
    (bottleneck_df["gsc_clicks"] == 0)
)

# ------------------------------------------------------------
# 3. Session diagnostic
# ------------------------------------------------------------
# Organic sessions are NOT treated as a conventional funnel
# conversion from GSC clicks.
#
# Instead, we identify observations where organic sessions
# are available and the observed session-to-click ratio is
# below the median of the eligible population.

bottleneck_df["session_diagnostic"] = (
    bottleneck_df["session_to_click_ratio"].notna() &
    (
        bottleneck_df["session_to_click_ratio"]
        < session_ratio_threshold
    )
)

# ------------------------------------------------------------
# 4. Engagement diagnostic
# ------------------------------------------------------------
# Engagement has very limited coverage (2.16%).
# Therefore it is treated as a diagnostic signal rather than
# a dominant bottleneck label.

bottleneck_df["engagement_diagnostic"] = (
    bottleneck_df["engaged_session_ratio"].notna() &
    (
        bottleneck_df["engaged_session_ratio"]
        < engagement_ratio_threshold
    )
)

# ------------------------------------------------------------
# 5. Availability flags
# ------------------------------------------------------------

bottleneck_df["visibility_evidence_available"] = (
    (bottleneck_df["gsc_impressions"] > 0) &
    bottleneck_df["gsc_avg_position"].notna()
)

bottleneck_df["click_evidence_available"] = (
    bottleneck_df["gsc_impressions"] > 0
)

bottleneck_df["session_evidence_available"] = (
    bottleneck_df["session_to_click_ratio"].notna()
)

bottleneck_df["engagement_evidence_available"] = (
    bottleneck_df["engaged_session_ratio"].notna()
)

print("Bottleneck indicators created.")

print("\nBottleneck counts")
print("-----------------")

print(
    "Visibility:",
    bottleneck_df["visibility_bottleneck"].sum()
)

print(
    "Click:",
    bottleneck_df["click_bottleneck"].sum()
)

print(
    "Session diagnostic:",
    bottleneck_df["session_diagnostic"].sum()
)

print(
    "Engagement diagnostic:",
    bottleneck_df["engagement_diagnostic"].sum()
)

Bottleneck indicators created.

Bottleneck counts
-----------------
Visibility: 861968
Click: 3193080
Session diagnostic: 107115
Engagement diagnostic: 191330

In [44]:
# ============================================================
# Section 3 — Methodology
# 11. Build the bottleneck score
# ============================================================

# Work on a copy so the indicator columns remain available.
score_df = bottleneck_df.copy()

# ------------------------------------------------------------
# Score components
# ------------------------------------------------------------
# Each observed bottleneck signal contributes one point.
#
# Visibility:
#   Poor relative position
#
# Click:
#   Impressions but zero clicks
#
# Session:
#   Below-median observed session-to-click ratio
#
# Engagement:
#   Below the observed 90th-percentile reference
#
# These are directional evidence signals, not causal effects.

score_df["visibility_score"] = (
    score_df["visibility_bottleneck"].astype(int)
)

score_df["click_score"] = (
    score_df["click_bottleneck"].astype(int)
)

score_df["session_score"] = (
    score_df["session_diagnostic"].astype(int)
)

score_df["engagement_score"] = (
    score_df["engagement_diagnostic"].astype(int)
)

# ------------------------------------------------------------
# Overall bottleneck score
# ------------------------------------------------------------

score_df["bottleneck_score"] = (
    score_df["visibility_score"]
    + score_df["click_score"]
    + score_df["session_score"]
    + score_df["engagement_score"]
)

print("Bottleneck score created.")

print("\nScore distribution")
print("------------------")

display(
    score_df["bottleneck_score"]
    .value_counts()
    .sort_index()
    .rename_axis("Bottleneck score")
    .reset_index(name="Rows")
)

Bottleneck score created.

Score distribution
------------------

   Bottleneck score     Rows
0                 0  6408062
1                 1  2530950
2                 2   884555
3                 3    17811

In [ ]:
# ============================================================
# 12. Convert overlapping signals into a primary bottleneck
# ============================================================

# Priority order:
# 1. Engagement
# 2. Session
# 3. Click
# 4. Visibility
#
# The order is used only to assign one primary reason when
# multiple bottleneck indicators occur in the same observation.

def assign_primary_bottleneck(row):

    if row["engagement_diagnostic"]:
        return "Engagement"

    elif row["session_diagnostic"]:
        return "Session"

    elif row["click_bottleneck"]:
        return "Click"

    elif row["visibility_bottleneck"]:
        return "Visibility"

    else:
        return "No identified bottleneck"


score_df["primary_bottleneck"] = score_df.apply(
    assign_primary_bottleneck,
    axis=1
)

print("Primary bottleneck assigned.")

primary_summary = (
    score_df["primary_bottleneck"]
    .value_counts()
    .rename_axis("Primary bottleneck")
    .reset_index(name="Rows")
)

primary_summary["Percentage (%)"] = (
    primary_summary["Rows"] /
    len(score_df) * 100
).round(2)

display(primary_summary)

## 4. Results (vs baseline)

*Model vs baseline on the same split. The honest table.*

## 5. Limitations

*What this work cannot claim.*

## 6. Ranked recommendations

*The action playbook output — the paper's recommendations section.*

## 7. Artifacts the paper embeds

*Generate/collect the charts and tables your deployed page will show.*

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.
- [ ] My deployed paper has **all 9 sections** — including the **Abstract** at the top and **Acknowledgments & data credit** (the https://flyrank.ai link) at the bottom.
- [ ] **ML-12 done in this notebook's closing cells:** 5-minute demo outline + a social-post cut + a 3-sentence employer-facing summary.